# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Garage-stripe"
client_id = "a548f9e51adb0a67ad8c16eebb5cdada"
application_url = "https://keno-configuration-social-gsm.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://keno-configuration-social-gsm.trycloudflare.com/auth/callback",
  "https://keno-configuration-social-gsm.trycloudflare.com/auth/shopify/callback",
  "https://keno-configuration-social-gsm.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[app_proxy]
url = "https://ubiquitous-donut-d43397.netlify.app/api"
subpath = "my_proxy"
prefix = "apps"

[pos]
embedded = false

[app_preferences]
url = "https://ubiquitous-donut-d43397.netlify.app/"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "garage-test-stripe.myshopify.com"
