# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Garage-stripe"
client_id = "a548f9e51adb0a67ad8c16eebb5cdada"
application_url = "https://feel-disable-una-deputy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://feel-disable-una-deputy.trycloudflare.com/auth/callback",
  "https://feel-disable-una-deputy.trycloudflare.com/auth/shopify/callback",
  "https://feel-disable-una-deputy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "garage-test-stripe.myshopify.com"
